adding support for Azure Billing
neuvector/neuvector-helm pull request #303
Opened 2023-08-30 00:26 UTC by selvamt94

2023-08-30 00:52 UTC, KeithMnemonic requested changes
Suggested updates if we want to simplify maintenance of the Charts needed to build the CNAB used to create the Azure offer:

See:  https://learn.microsoft.com/en-us/partner-center/marketplace/azure-container-technical-assets-kubernetes?tabs=linux#update-the-helm-chart

2023-08-30 00:52 UTC, KeithMnemonic commented on charts/core/README.md
> +`global.azurebilling.image.repository` | csp adapter image repository | `neuvector/neuvector-csp-adapter` | Follow Azure subscription instruction
If we do not want to maintain a seperate fork or branch for building the CNAB for Azure, we need to follow these guidelines.  https://learn.microsoft.com/en-us/partner-center/marketplace/azure-container-technical-assets-kubernetes?tabs=linux#update-the-helm-chart

2023-08-30 00:52 UTC, KeithMnemonic commented on charts/core/templates/csp-deployment.yaml
>        containers:
If we do not want to maintain a seperate fork or branch for building the CNAB for Azure, we need to follow these guidelines. https://learn.microsoft.com/en-us/partner-center/marketplace/azure-container-technical-assets-kubernetes?tabs=linux#update-the-helm-chart

we need to add in some extra env variables here or using somethibg like

        # envFrom:
        #   - configMapRef:
        #       name: neuvector-csp-pod
        env:

2023-08-30 00:52 UTC, KeithMnemonic commented on charts/core/values.yaml
> +  azurebilling:
We need to follow the naming structure Microsoft dictates for the CNAB

https://learn.microsoft.com/en-us/partner-center/marketplace/azure-container-technical-assets-kubernetes?tabs=linux#update-the-helm-chart

2023-09-05 15:28 UTC, garyduan commented
I suggest we move the AWS billing parameters to 'global' as well.

2023-09-07 16:26 UTC, KeithMnemonic commented on charts/core/values.yaml
> +  azurebilling:
we need to change `azurebilling` to `azure`

2023-09-20 18:45 UTC, KeithMnemonic commented
@selvamt94 I tested this with the neuvector2 plan and it deployed successfully and I can see it billed.

2023-09-20T18:42:35.239|INFO|CSPBillingAdapter|Attempt a billing cycle update
2023-09-20T18:42:35.241|INFO|CSPBillingAdapter|Filtering records for 2023-09-20T17:42:32.076781+00:00 <= reporting_time < 2023-09-20T18:42:32.076781+00:00
2023-09-20T18:42:35.241|INFO|CSPBillingAdapter|Metric: 'managed_node_count', average = 3, records: [{'base_product': 'cpe:/o:suse:neuvector:5.2.0', 'managed_node_count': 3, 'reporting_time': '2023-09-20T18:22:36.472852+00:00'}]
2023-09-20T18:42:35.241|INFO|CSPBillingAdapter|Billable usage: {'managed_node_count': 5}, records: [{'base_product': 'cpe:/o:suse:neuvector:5.2.0', 'managed_node_count': 3, 'reporting_time': '2023-09-20T18:22:36.472852+00:00'}]
2023-09-20T18:42:35.241|INFO|CSPBillingAdapter|Metric: managed_node_count=5, Volume dimension: 5
2023-09-20T18:42:35.241|INFO|CSPBillingAdapter|Determined billable dimensions {'tier_1': 5} for usage {'managed_node_count': 5}
2023-09-20T18:42:36.386|INFO|CSPBillingAdapter|New metered billing record added with ID 37b01ec7-67b9-4129-9401-d343385ae2c2:
2023-09-20T18:42:36.386|INFO|CSPBillingAdapter|Metering submitted, record_id: {'tier_1': {'record_id': '37b01ec7-67b9-4129-9401-d343385ae2c2', 'status': 'submitted'}}

2023-09-27 15:45 UTC, jeremy-moffitt commented
@selvamt70 Keith and Yoga tell me that they've tested these changes and are happy with them. What else is needed to get this PR merged?

2023-09-27 15:48 UTC, brett060102 approved these changes
Change LGTM and has passed testing by Keith and Yoga's testing.

2023-09-27 15:49 UTC, KeithMnemonic approved these changes
LGTM

2023-09-28 22:53 UTC, merged